# Generated by Django 2.2.4 on 2019-08-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, help_text='Fecha de creacion del modelo', verbose_name='created at')),
                ('modified', models.DateField(auto_now=True, help_text='Fecha de actualizacion del modelo', verbose_name='created at')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatosEncuestado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, help_text='Fecha de creacion del modelo', verbose_name='created at')),
                ('modified', models.DateField(auto_now=True, help_text='Fecha de actualizacion del modelo', verbose_name='created at')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('H', 'HOMBRE'), ('M', 'MUJER')], default='H', max_length=1)),
                ('email', models.EmailField(max_length=200)),
                ('tiene_hijos', models.BooleanField(default=False)),
                ('edad_hijos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.Ciudad')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, help_text='Fecha de creacion del modelo', verbose_name='created at')),
                ('modified', models.DateField(auto_now=True, help_text='Fecha de actualizacion del modelo', verbose_name='created at')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, help_text='Fecha de creacion del modelo', verbose_name='created at')),
                ('modified', models.DateField(auto_now=True, help_text='Fecha de actualizacion del modelo', verbose_name='created at')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='opciones_respuestas/')),
            ],
            options={
                'ordering': ['id'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, help_text='Fecha de creacion del modelo', verbose_name='created at')),
                ('modified', models.DateField(auto_now=True, help_text='Fecha de actualizacion del modelo', verbose_name='created at')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=150)),
                ('respuestas_multiples', models.BooleanField(default=False)),
                ('max_respuestas', models.PositiveIntegerField(default=0)),
                ('tipo_respuesta', models.CharField(max_length=10)),
                ('especifica', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='preguntas/')),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encuesta.Pregunta')),
                ('encuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='encuesta.Encuesta')),
            ],
            options={
                'ordering': ['id'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, help_text='Fecha de creacion del modelo', verbose_name='created at')),
                ('modified', models.DateField(auto_now=True, help_text='Fecha de actualizacion del modelo', verbose_name='created at')),
                ('detalle_respuesta', models.CharField(blank=True, max_length=250, null=True)),
                ('encuestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.DatosEncuestado')),
                ('opcion_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encuesta.OpcionRespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.Pregunta')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='encuesta.Pregunta'),
        ),
        migrations.AddField(
            model_name='datosencuestado',
            name='encuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.Encuesta'),
        ),
    ]
