# Generated by Django 2.2.4 on 2019-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='especifica',
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='especifica',
            field=models.BooleanField(default=False),
        ),
    ]
