# Generated by Django 2.2.4 on 2019-08-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_auto_20190818_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='especifica',
            field=models.BooleanField(default=False),
        ),
    ]
