# Generated by Django 2.2.4 on 2019-08-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_pregunta_especifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='relacion_pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuesta_relacionada', to='encuesta.Pregunta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='encuestado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='encuesta.DatosEncuestado'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta', to='encuesta.Pregunta'),
        ),
    ]
