# Generated by Django 2.2.4 on 2019-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_auto_20190819_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosencuestado',
            name='edad_hijos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
