# Generated by Django 2.2.4 on 2019-08-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0005_auto_20190819_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionrespuesta',
            name='genero',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
