# Generated by Django 2.2.4 on 2019-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0006_opcionrespuesta_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='edad_desde',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='edad_hasta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='valida_edad',
            field=models.BooleanField(default=False),
        ),
    ]
