# Generated by Django 2.2.4 on 2019-08-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0007_auto_20190819_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosencuestado',
            name='edad_hijos',
            field=models.CharField(choices=[('H', 'HOMBRE'), ('M', 'MUJER')], default='H', max_length=1),
        ),
    ]
