# Generated by Django 2.2.4 on 2019-08-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0008_auto_20190819_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosencuestado',
            name='genero_hijo',
            field=models.CharField(choices=[('H', 'HOMBRE'), ('M', 'MUJER')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='datosencuestado',
            name='edad_hijos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
